FROM nginx:stable-alpine

RUN adduser -D -u 1001 -g 'usuariocomum' usuariocomum

WORKDIR /usr/share/nginx/html

RUN chown -R usuariocomum:usuariocomum /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /run/nginx && \
    chown -R usuariocomum:usuariocomum /run/nginx && \
    mkdir -p /var/cache/nginx && \
    chown -R usuariocomum:usuariocomum /var/cache/nginx && \
    mkdir -p /var/log/nginx && \
    chown -R usuariocomum:usuariocomum /var/log/nginx && \
    mkdir -p /etc/nginx/conf.d && \
    chown -R usuariocomum:usuariocomum /etc/nginx/conf.d && \
    chown -R usuariocomum:usuariocomum /etc/nginx/nginx.conf && \
    mkdir -p /var/lib/nginx && \
    chown -R usuariocomum:usuariocomum /var/lib/nginx

RUN touch /var/run/nginx.pid && chown usuariocomum:usuariocomum /var/run/nginx.pid

USER usuariocomum

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

