version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
      - net-api

  net-api:
    build:
      context: ./WEBAPI/TaskManager
    expose:
      - "5000"
    networks:
      - app-network
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/TarefasDB
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - mongodb

  react-app:
    build:
      context: ./WEBAPP/task-viewer
    expose:
      - "3000"
    networks:
      - app-network
    environment:
      - REACT_APP_NET_APP_URL=http://nginx:80

  mongodb:
    image: mongo:4.4
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  app-network: